### ISSUE TITLE
Add warranty 

### ISSUE THREAD

**Issue by oliviagallucci** [g0ldencybersec/EasyEASM#3]
Prolly good idea to add a warranty... 

I welcome folks to copy mine word-for-word, but your project uses MIT license (and not GPLv3), so you can't copy. I'd just look for one w MIT, and you should be set.

[https://github.com/oliviagallucci/README#warranty](https://github.com/oliviagallucci/README#warranty)

**Comment by oliviagallucci** [comment]
Also, BTW I can implement this.

I just want permission to do so, LOL.

**Comment by oliviagallucci** [comment]
@g0ldencybersec ^

**Comment by g0ldencybersec** [comment]
Yes please go right ahead :)

**Comment by oliviagallucci** [comment]
Completed
