### ISSUE TITLE
panic: exec: "subfinder": executable file not found in $PATH

### ISSUE THREAD

**Issue by aburroughs** [g0ldencybersec/EasyEASM#7]
After running ./easyeasm I get the following:

subfinder is not installed
2023/08/15 13:11:40 Successfully installed the package: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
dnsx is not installed
2023/08/15 13:11:41 Successfully installed the package: github.com/projectdiscovery/dnsx/cmd/dnsx@latest
alterx is not installed
2023/08/15 13:11:47 Successfully installed the package: github.com/projectdiscovery/alterx/cmd/alterx@latest
All needed tools installed!

No previous run data found
Running Passive Sources
Finding domains for example.com
Runing Subfinder on example.com
Running Amass on example.com
panic: exec: "subfinder": executable file not found in $PATH

goroutine 20 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/subfinder.RunSubfinder({0xc000190300, 0xd}, 0x0?, 0x0?)
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/passive/subfinder/subfinder.go:21 +0x33e
created by github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunPassiveEnum
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/passive/passive.go:26 +0x1ee

All exes are present in the /go/bin dir

**Comment by g0ldencybersec** [comment]
Ah yes during Go installation you want to make sure that you add your binary directory for downloaded tools to your PATH. 
The above error shows that go binaries are not in your $PATH yet.
```
export PATH=$PATH:$(go env GOPATH)/bin
```

I would recommend adding this to your ~/.profile or ~/.bashrc file so that this happens automatically!

**Comment by g0ldencybersec** [comment]
This should put that /go/bin directory in your path! Running easyeasm again should work after your PATH is set!

**Comment by oliviagallucci** [comment]
Should I close this issue?

**Comment by aburroughs** [comment]
Yes thank you!

I did have a general question not really an issue. I could not find the CSV
file generated only a text file is generated in the go/bin directory.

Am I missing something? Or is it generated elsewhere?

**Comment by g0ldencybersec** [comment]
Assuming the tool finishes a run, then there should be a CSV file called "EasyEASM.csv" in whatever directory you ran the tool from!

**Comment by aburroughs** [comment]
Yes it runs and outputs on screen but only generates a txt file that I can
cat but nothing of csv file type. Should I be importing some module to do
this?

**Comment by g0ldencybersec** [comment]
Can you copy in the text of you running the tool? And also a 'ls' run after the fact as well

**Comment by aburroughs** [comment]
Here is the output after a successful running of ./easyeasm:

goroutine 1 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/passive/httpx.RunHttpx({0xc0002c8000?, 0xc000124008?, 0xc000157ae8?})
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/passive/httpx/httpx.go:16 +0x187
github.com/g0ldencybersec/EasyEASM/pkg/passive.(*PassiveRunner).RunHttpx(...)
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/passive/passive.go:59
main.main()
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/easyeasm/main.go:60 +0xfb6

Here is the output of ls:
                                                                             
┌──(kali㉿kali)-[~/go/bin]
└─$ ls
alterx  config.yml  dnsx  easyeasm  subfinder  tempHttpx.txt

**Comment by g0ldencybersec** [comment]
Ah... The tool is still failing on the step where it runs httpx. I think the reason for this is that kali comes with a pre-installed httpx that is written in python and different than the one the tool wants. BUT since there was a tool called "httpx" in your $PATH, the tool didn't install the right one. That is why I don't see a httpx binary in your /go/bin

If you would for me, try running: ```go install github.com/projectdiscovery/httpx/cmd/httpx@latest```

Then run the tool again. See if it doesn't error and generates the csv correctly :) If that fixes it I will add a chunk in the README!!

**Comment by aburroughs** [comment]
I ran `go install github.com/projectdiscovery/httpx/cmd/httpx@latest` successfully but still getting a tempHttpx.txt file in the directory after successful completion instead of a generated csv file. 

Here is the last chunk of output: 

```
Checking which domains are live and generating assets csv...
panic: exit status 2

```
goroutine 1 [running]:
github.com/g0ldencybersec/EasyEASM/pkg/active/httpx.RunHttpx({0xc0001a6a00?, 0xc000014018?, 0xc00012dab8?})
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/active/httpx/httpx.go:16 +0x187
github.com/g0ldencybersec/EasyEASM/pkg/active.(*ActiveRunner).RunHttpx(...)
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/pkg/active/active.go:24
main.main()
        /home/kali/go/pkg/mod/github.com/g0ldencybersec/!easy!e!a!s!m@v1.0.4/easyeasm/main.go:102 +0xc07
```
```

**Comment by g0ldencybersec** [comment]
I think you still are running the wrong httpx. You have to delete the python version that comes with kali

I think running ```which httpx``` will tell you where it is

**Comment by oliviagallucci** [comment]
This resolved? @g0ldencybersec @aburroughs

**Comment by aburroughs** [comment]
Yes - removing the built in httpx in usr/bin on Kali worked!
